passwordToKey: "![haao+2L4ImTaMYlJhNE/EA==]"
passwordToKeyStore: "![haao+2L4ImTaMYlJhNE/EA==]"
passwordToTrustStore: "![sw2g7njR5FjUx7tafTMLkHqAsw9PRWe2/9mdmwqOKgQ=]"


 
bpldsmembershipInfo:
  clientSecret: "![BhjXsESRAvd1Pabg8Wn9Ji3Ug0lWavgJ0RdFLT3zgLE9N3YhcWgy9SYpYDpz4bhv]"

security:
  password : "![Vq4UN6mrRq6eY+fHOydBKw==]" 