passwordToKey: "![MuCb9GjkHuDVFtR/OTgRAA==]"
passwordToKeyStore: "![MuCb9GjkHuDVFtR/OTgRAA==]"
passwordToTrustStore: "![MuCb9GjkHuDVFtR/OTgRAA==]"



bpldsmembershipInfo:
  clientSecret: "password"

security:
  password : "password"