passwordToKey: "![C5FErRHKuSQbMQR/4N4l/w==]"
passwordToKeyStore: "![C5FErRHKuSQbMQR/4N4l/w==]"
passwordToTrustStore: "![OAh58VDGxnaLlqfAvttmzA==]"

bpldsmembershipInfo:
  clientSecret: "![nLSQ14hm+5OFjmYuqiNVnPwJvmd0jFa/E0qF/e0mc51MSRrL4vOHgczbZGH8njeQ]"
security:
  password : "![x6njmFGFPj94ubtiTECLjw==]" 