<?xml version="1.0" encoding="UTF-8"?><definitions name="RetrieveAlphaPrefix" targetNamespace="urn:service.cs.bcbsm.com" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:rap="urn:rtrvalphaprefix2_0.elig.schema.bcbsm.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:service.cs.bcbsm.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:rtrvalphaprefix2_0.elig.schema.bcbsm.com" schemaLocation="elig/RtrvAlphaPrefixTypes-v2.0.xsd"/>
        </xsd:schema>
    </types>

    <message name="RtrvAlphaPrefixRequest">
        <part element="rap:RtrvAlphaPrefixRequest" name="request"/>
    </message>
    <message name="RtrvAlphaPrefixResponse">
        <part element="rap:RtrvAlphaPrefixResponse" name="response"/>
    </message>
    <portType name="rtrvAlphaPrefixService">
        <operation name="doTransaction" parameterOrder="request">
            <input message="tns:RtrvAlphaPrefixRequest" name="doTransactionRequest"/>
            <output message="tns:RtrvAlphaPrefixResponse" name="doTransactionResponse"/>
        </operation>
    </portType>
    <binding name="rtrvAlphaPrefixBinding" type="tns:rtrvAlphaPrefixService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="doTransaction">
            <soap:operation soapAction="urn:service.cs.bcbsm.com/doTransaction"/>
            <input name="doTransactionRequest">
                <soap:body use="literal"/>
            </input>
            <output name="doTransactionResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="RtrvAlphaPrefix">
        <port binding="tns:rtrvAlphaPrefixBinding" name="RtrvAlphaPrefixPort">
            <soap:address location="http://localhost:9081/RtrvAlphaPrefixWeb/services/RtrvAlphaPrefixPort"/>
        </port>
    </service>
</definitions>